apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-app-pdb
spec:
  minAvailable: 2  # Минимум 2 пода должны быть доступны всегда
  selector:
    matchLabels:
      app: web-app
